#!/usr/bin/env python

import sys

# Number of letters in each part, we don't count spaces
Decades = ( 0, 3, 6, 6, 6, 5, 5, 7, 6, 6, 0 )
Smalls  = ( 0, 3, 3, 5, 4, 4, 3, 5, 5, 4 )
Teens  =  ( 6, 6, 8, 8, 7, 7, 9, 8, 8 )


def Count(n):
    if n > 10 and n < 20:
       return Teens[n-11]
    return  Smalls[n % 10 ] + Decades [ n / 10 ]




N = int(sys.argv[1])

while not N == 4:
    Cnt = Count(N)
    print "%d is %d" % ( N, Cnt)
    N = Cnt

print "4 is magic"

